workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $CI_COMMIT_BRANCH =~ /^manticore-.*$/ && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $TEST
    - if: $WHAT

# to skip ci add [ci skip] or [skip ci] in commit message in any capitalization,
# or add param when pushing, as: git push -o ci.skip ...

variables:
  DOCS_AUTOCOMMIT_TITLE: 'Docs_examples_update'
  DOCS_EXAMPLES_FILEPATH: 'build/test/examples.txt'
  VERBOSE: 1

stages:
  - mirroring
  - hooks

# ==================== Mirror repo to github (only 'master' branch) ======================

job_mirror:
  stage: mirroring
  needs: [ ]
  rules:
    - if: $TEST==null && $CI_COMMIT_BRANCH == "master"
    - if: $TEST==null && $CI_COMMIT_BRANCH =~ /^manticore-.*$/
  tags:
    - dev-host
  script:
    - rm -fr gitlab_github_sync
    - git clone git@gitlab.com:manticoresearch/dev.git gitlab_github_sync
    - cd gitlab_github_sync
    - git checkout $CI_COMMIT_BRANCH
    - git remote add github git@github.com:manticoresoftware/manticoresearch.git
    - git fetch github
    - git push -u github $CI_COMMIT_BRANCH
  cache: {}

# ==================== Run secondary pipeline ======================

deploy_hook:
  stage: hooks
  variables:
    WHAT: $WHAT
    REPO_NAME: $REPO_NAME
  rules:
    - if: $CI_COMMIT_TITLE !~ /^noci .*$/i
      when: on_success
  trigger:
    include: dist/gitlab-release.yml
